language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
#  - git clone https://github.com/bportaluri/WiFiEsp $HOME/arduino_ide/libraries/WiFiEsp
  - arduino --install-library "WiFiEsp"
script:
  - build_platform esp8266
#  - build_platform uno
# - arduino --install-library "WiFiEsp"
# - arduino --install-library "ESP8266WiFi"
# - arduino --verify --board arduino:avr:uno $PWD/examples/ArduinoEspWifiShield/ArduinoEspWifiShield.ino
# - arduino --verify --board esp8266:esp8266:nodemcuv2 $PWD/examples/NodeMCU/NodeMCU.ino
notifications:
  email:
    on_success: change
    on_failure: change