language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
- build_platform esp8266
- build_platform arduino
# - arduino --install-library "WiFiEsp"
# - arduino --install-library "ESP8266WiFi"
# - arduino --verify --board arduino:avr:uno $PWD/examples/ArduinoEspWifiShield/ArduinoEspWifiShield.ino
# - arduino --verify --board esp8266:esp8266:nodemcuv2 $PWD/examples/NodeMCU/NodeMCU.ino
notifications:
  email:
    on_success: change
    on_failure: change